version: '3.8'

services:
  # Фронтенд приложение
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskmanager-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx для проксирования (опционально)
  nginx:
    image: nginx:alpine
    container_name: taskmanager-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - with-nginx

networks:
  app-network:
    driver: bridge

volumes:
  # Можно добавить volumes для данных, если понадобится
  app-data:
    driver: local
